export const TODOS_DATA = 'TODOS_DATA';
export const CREATE_TODOS_DATA = 'CREATE_TODOS_DATA';
export const DELETE_TODOS_DATA = 'DELETE_TODOS_DATA';
export const DELETE_SINGLE_TODOS_DATA = 'DELETE_SINGLE_TODOS_DATA';
export const REGISTER_FORM = 'REGISTER_FORM';
export const CREATE_CARD = 'CREATE_CARD';
export const FETCH_CARD = 'FETCH_CARD';